# .github/workflows/ci.yml

name: CI Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Sets up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use a recent LTS version
          cache: 'npm'

      # 3. Installs dependencies using npm ci (clean install)
      - name: Install dependencies
        run: npm ci

      # 4. Runs the build command to create a production build
      - name: Build project
        run: npm run build

      # 5. Optional: Run linter (if you have one configured)
      # - name: Run linter
      #   run: npm run lint

      # 6. Optional: Run tests (if you have them configured)
      # - name: Run tests
      #   run: npm run test